// auto-generated by gen_ct_drivers.py — linear if_match only
#include <array>
#include <string_view>
#include <utility>
using namespace std::literals;
constexpr std::array<std::string_view, 100> kKeys{
    "550e8400-e29b-41d4-a716-446655440000"sv,
    "123e4567-e89b-12d3-a456-426614174000"sv,
    "9f1c2d3e-4b5a-4c6d-8e7f-1029384756aa"sv,
    "7a8b9c0d-1e2f-4a3b-9c8d-776655443322"sv,
    "de305d54-75b4-431b-adb2-eb6b9e546014"sv,
    "0f8fad5b-d9cb-469f-a165-70867728950e"sv,
    "3d6f0a21-7c4b-4e19-9d2a-88c1ef7b5a60"sv,
    "a987fbc9-4bed-4078-8f07-9141ba07c9f3"sv,
    "6ba7b810-9dad-11d1-80b4-00c04fd430c8"sv,
    "6ba7b811-9dad-11d1-80b4-00c04fd430c8"sv,
    "16fd2706-8baf-433b-82eb-8c7fada847da"sv,
    "886313e1-3b8a-5372-9b90-0c9aee199e5d"sv,
    "c4a760a8-dbcf-44d0-9f3d-6b7e2c1a9d55"sv,
    "f47ac10b-58cc-4372-a567-0e02b2c3d479"sv,
    "2c1f9864-52d7-4d8a-bf3e-1a9c7e5d4b20"sv,
    "8d92f3a1-6b4c-4e7d-9f20-3c5a7b1e8d44"sv,
    "b1d2c3e4-f5a6-4789-8abc-def012345678"sv,
    "4e2d1c0b-9a8f-4765-b432-10fedcba9876"sv,
    "d3b07384-d9a2-4c6f-8e1b-5a7c9d2e4f60"sv,
    "fe12ab34-cd56-4789-90ef-1234567890ab"sv,
    "0a1b2c3d-4e5f-4789-8abc-001122334455"sv,
    "1b2c3d4e-5f60-489a-9bcd-112233445566"sv,
    "2c3d4e5f-6071-49ab-acde-223344556677"sv,
    "3d4e5f60-7182-4abc-bdef-334455667788"sv,
    "4e5f6071-8293-4bcd-8ef0-445566778899"sv,
    "5f607182-93a4-4cde-9f01-5566778899aa"sv,
    "60718293-a4b5-4def-af12-66778899aabb"sv,
    "718293a4-b5c6-4ef0-b123-778899aabbcc"sv,
    "8293a4b5-c6d7-4f01-8123-8899aabbccdd"sv,
    "93a4b5c6-d7e8-4012-9234-99aabbccddee"sv,
    "a4b5c6d7-e8f9-4123-a345-aabbccddeeff"sv,
    "b5c6d7e8-f90a-4234-b456-bbccddeeff00"sv,
    "c6d7e8f9-0a1b-4345-8456-ccddeeff0011"sv,
    "d7e8f90a-1b2c-4456-9567-ddeeff001122"sv,
    "e8f90a1b-2c3d-4567-a678-eeff00112233"sv,
    "f90a1b2c-3d4e-4678-b789-ff0011223344"sv,
    "0b1c2d3e-4f50-4789-8899-102132435465"sv,
    "1c2d3e4f-5061-489a-99aa-213243546576"sv,
    "2d3e4f50-6172-49ab-aabb-324354657687"sv,
    "3e4f5061-7283-4abc-bbcc-435465768798"sv,
    "4f506172-8394-4bcd-8ccd-5465768798a9"sv,
    "50617283-94a5-4cde-9dde-65768798a9ba"sv,
    "61728394-a5b6-4def-aeef-768798a9bacb"sv,
    "728394a5-b6c7-4ef0-bff0-8798a9bacbdc"sv,
    "8394a5b6-c7d8-4f01-8011-98a9bacbdced"sv,
    "94a5b6c7-d8e9-4012-9122-a9bacbdcedfe"sv,
    "a5b6c7d8-e9fa-4123-a233-bacbdcedfe0f"sv,
    "b6c7d8e9-fa0b-4234-b344-cbdcedfe0f10"sv,
    "c7d8e9fa-0b1c-4345-8455-dcedfe0f1021"sv,
    "d8e9fa0b-1c2d-4456-9566-edfe0f102132"sv,
    "e9fa0b1c-2d3e-4567-a677-fe0f10213243"sv,
    "fa0b1c2d-3e4f-4678-b788-0f1021324354"sv,
    "ab10cd20-ef30-4789-8a40-123451234512"sv,
    "bc21de31-f041-489a-9b51-234562345623"sv,
    "cd32ef42-0152-49ab-ac62-345673456734"sv,
    "de43f053-1263-4abc-bd73-456784567845"sv,
    "ef540164-2374-4bcd-8e84-567895678956"sv,
    "f0651275-3485-4cde-9f95-6789a6789a67"sv,
    "10662186-4596-4def-a0a6-789ab789ab78"sv,
    "21773297-56a7-4ef0-b1b7-89abc89abc89"sv,
    "328843a8-67b8-4f01-82c8-9abcd9abcd9a"sv,
    "439954b9-78c9-4012-93d9-abcdedabcdea"sv,
    "54aa65ca-89da-4123-a4ea-bcdefebcdefb"sv,
    "65bb76db-9aeb-4234-b5fb-cdef0fcdef0c"sv,
    "76cc87ec-abfc-4345-860c-def120def120"sv,
    "87dd98fd-bc0d-4456-971d-ef2311ef2311"sv,
    "98eea90e-cd1e-4567-a82e-f34222f34222"sv,
    "a9ffba1f-de2f-4678-b93f-043333043333"sv,
    "ba10cb20-ef30-4789-8a40-154444154444"sv,
    "cb21dc31-f041-489a-9b51-265555265555"sv,
    "13579bdf-2468-4ace-8fed-0123456789ab"sv,
    "2468ace0-1357-4bdf-9cfe-123456789abc"sv,
    "3579bdf1-0246-4cea-ad0f-23456789abcd"sv,
    "468ace02-1357-4dfb-be10-3456789abcde"sv,
    "579bdf13-2468-4eac-8f21-456789abcdef"sv,
    "68ace024-3579-4fbd-9032-56789abcdef0"sv,
    "79bdf135-468a-40ce-a143-6789abcdef01"sv,
    "8ace0246-579b-41df-b254-789abcdef012"sv,
    "9bdf1357-68ac-42e0-8365-89abcdef0123"sv,
    "ace02468-79bd-43f1-9476-9abcdef01234"sv,
    "bdf13579-8ace-4502-a587-abcdef012345"sv,
    "ce02468a-9bdf-4613-b698-bcdef0123456"sv,
    "df13579b-ace0-4724-87a9-cdef01234567"sv,
    "e02468ac-bdf1-4835-98ba-def012345678"sv,
    "f13579bd-ce02-4946-a9cb-ef0123456789"sv,
    "02468ace-df13-4a57-badc-f0123456789a"sv,
    "11111111-2222-4333-8444-555555555555"sv,
    "22222222-3333-4444-8555-666666666666"sv,
    "33333333-4444-4555-8666-777777777777"sv,
    "44444444-5555-4666-8777-888888888888"sv,
    "55555555-6666-4777-8888-999999999999"sv,
    "66666666-7777-4888-8999-aaaaaaaaaaaa"sv,
    "77777777-8888-4999-8aaa-bbbbbbbbbbbb"sv,
    "88888888-9999-4aaa-8bbb-cccccccccccc"sv,
    "99999999-aaaa-4bbb-8ccc-dddddddddddd"sv,
    "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"sv,
    "bbbbbbbb-cccc-4ddd-8eee-ffffffffffff"sv,
    "cccccccc-dddd-4eee-8fff-000000000000"sv,
    "dddddddd-eeee-4fff-8000-111111111111"sv,
    "eeeeeeee-ffff-4000-8111-222222222222"sv,
};
template<std::size_t... I>
bool dispatch_impl(std::string_view v, std::index_sequence<I...>) {
    return ((v == kKeys[I]) || ...);
}
bool dispatch(std::string_view v) {
    return dispatch_impl(v, std::make_index_sequence<100>{});
}
std::string_view kHit0 = "550e8400-e29b-41d4-a716-446655440000";
std::string_view kHit1 = "eeeeeeee-ffff-4000-8111-222222222222";
std::string_view kMiss = "ffffffff-ffff-4fff-8fff-ffffffffffff";

int main() {
  volatile bool r = dispatch(kHit0);
  r = dispatch(kHit1);
  r = dispatch(kMiss);
  return r ? 0 : 0;
}
