// auto-generated by gen_ct_drivers.py — glaze perfect hash only
#include <glaze/core/opts.hpp>
#include <glaze/core/reflect.hpp>
#include <array>
#include <cstddef>
#include <string_view>
#include <tuple>
#include <utility>
using namespace std::literals;
constexpr std::array<std::string_view, 100> kKeys{
    "01"sv,
    "02"sv,
    "03"sv,
    "04"sv,
    "05"sv,
    "06"sv,
    "07"sv,
    "08"sv,
    "09"sv,
    "10"sv,
    "11"sv,
    "12"sv,
    "13"sv,
    "14"sv,
    "15"sv,
    "16"sv,
    "17"sv,
    "18"sv,
    "19"sv,
    "20"sv,
    "21"sv,
    "22"sv,
    "23"sv,
    "24"sv,
    "25"sv,
    "26"sv,
    "27"sv,
    "28"sv,
    "29"sv,
    "30"sv,
    "31"sv,
    "32"sv,
    "33"sv,
    "34"sv,
    "35"sv,
    "36"sv,
    "37"sv,
    "38"sv,
    "39"sv,
    "40"sv,
    "41"sv,
    "42"sv,
    "43"sv,
    "44"sv,
    "45"sv,
    "46"sv,
    "47"sv,
    "48"sv,
    "49"sv,
    "50"sv,
    "51"sv,
    "52"sv,
    "53"sv,
    "54"sv,
    "55"sv,
    "56"sv,
    "57"sv,
    "58"sv,
    "59"sv,
    "60"sv,
    "61"sv,
    "62"sv,
    "63"sv,
    "64"sv,
    "65"sv,
    "66"sv,
    "67"sv,
    "68"sv,
    "69"sv,
    "70"sv,
    "71"sv,
    "72"sv,
    "73"sv,
    "74"sv,
    "75"sv,
    "76"sv,
    "77"sv,
    "78"sv,
    "79"sv,
    "80"sv,
    "81"sv,
    "82"sv,
    "83"sv,
    "84"sv,
    "85"sv,
    "86"sv,
    "87"sv,
    "88"sv,
    "89"sv,
    "90"sv,
    "91"sv,
    "92"sv,
    "93"sv,
    "94"sv,
    "95"sv,
    "96"sv,
    "97"sv,
    "98"sv,
    "99"sv,
    "00"sv,
};
using keys_t = glz::keys_wrapper<kKeys>;
constexpr auto& kInfo = glz::hash_info<keys_t>;

volatile std::size_t g_sink = 0;

template <std::size_t I> struct BenchFn {
  void operator()() const noexcept { g_sink += I + 1; }
};

template <std::size_t... I>
auto make_commands_impl(std::index_sequence<I...>) {
  return std::tuple{BenchFn<I>{}...};
}

using commands_t = decltype(make_commands_impl(
    std::make_index_sequence<kKeys.size()>{}));

auto make_commands() -> commands_t {
  return make_commands_impl(std::make_index_sequence<kKeys.size()>{});
}

std::string_view kHit0 = "03";
std::string_view kHit1 = "26";
std::string_view kMiss = "0a";

void lookup(std::string_view v, commands_t& commands) {
  const auto index =
      glz::decode_hash_with_size<glz::JSON, keys_t, kInfo, kInfo.type>::op(
      v.data(), v.data() + v.size(), v.size());
  if (index >= kKeys.size()) {
    return;
  }
  if (kKeys[index] != v) {
    return;
  }

  switch (index) {
  case 0:
    std::get<0>(commands)();
    return;
  case 1:
    std::get<1>(commands)();
    return;
  case 2:
    std::get<2>(commands)();
    return;
  case 3:
    std::get<3>(commands)();
    return;
  case 4:
    std::get<4>(commands)();
    return;
  case 5:
    std::get<5>(commands)();
    return;
  case 6:
    std::get<6>(commands)();
    return;
  case 7:
    std::get<7>(commands)();
    return;
  case 8:
    std::get<8>(commands)();
    return;
  case 9:
    std::get<9>(commands)();
    return;
  case 10:
    std::get<10>(commands)();
    return;
  case 11:
    std::get<11>(commands)();
    return;
  case 12:
    std::get<12>(commands)();
    return;
  case 13:
    std::get<13>(commands)();
    return;
  case 14:
    std::get<14>(commands)();
    return;
  case 15:
    std::get<15>(commands)();
    return;
  case 16:
    std::get<16>(commands)();
    return;
  case 17:
    std::get<17>(commands)();
    return;
  case 18:
    std::get<18>(commands)();
    return;
  case 19:
    std::get<19>(commands)();
    return;
  case 20:
    std::get<20>(commands)();
    return;
  case 21:
    std::get<21>(commands)();
    return;
  case 22:
    std::get<22>(commands)();
    return;
  case 23:
    std::get<23>(commands)();
    return;
  case 24:
    std::get<24>(commands)();
    return;
  case 25:
    std::get<25>(commands)();
    return;
  case 26:
    std::get<26>(commands)();
    return;
  case 27:
    std::get<27>(commands)();
    return;
  case 28:
    std::get<28>(commands)();
    return;
  case 29:
    std::get<29>(commands)();
    return;
  case 30:
    std::get<30>(commands)();
    return;
  case 31:
    std::get<31>(commands)();
    return;
  case 32:
    std::get<32>(commands)();
    return;
  case 33:
    std::get<33>(commands)();
    return;
  case 34:
    std::get<34>(commands)();
    return;
  case 35:
    std::get<35>(commands)();
    return;
  case 36:
    std::get<36>(commands)();
    return;
  case 37:
    std::get<37>(commands)();
    return;
  case 38:
    std::get<38>(commands)();
    return;
  case 39:
    std::get<39>(commands)();
    return;
  case 40:
    std::get<40>(commands)();
    return;
  case 41:
    std::get<41>(commands)();
    return;
  case 42:
    std::get<42>(commands)();
    return;
  case 43:
    std::get<43>(commands)();
    return;
  case 44:
    std::get<44>(commands)();
    return;
  case 45:
    std::get<45>(commands)();
    return;
  case 46:
    std::get<46>(commands)();
    return;
  case 47:
    std::get<47>(commands)();
    return;
  case 48:
    std::get<48>(commands)();
    return;
  case 49:
    std::get<49>(commands)();
    return;
  case 50:
    std::get<50>(commands)();
    return;
  case 51:
    std::get<51>(commands)();
    return;
  case 52:
    std::get<52>(commands)();
    return;
  case 53:
    std::get<53>(commands)();
    return;
  case 54:
    std::get<54>(commands)();
    return;
  case 55:
    std::get<55>(commands)();
    return;
  case 56:
    std::get<56>(commands)();
    return;
  case 57:
    std::get<57>(commands)();
    return;
  case 58:
    std::get<58>(commands)();
    return;
  case 59:
    std::get<59>(commands)();
    return;
  case 60:
    std::get<60>(commands)();
    return;
  case 61:
    std::get<61>(commands)();
    return;
  case 62:
    std::get<62>(commands)();
    return;
  case 63:
    std::get<63>(commands)();
    return;
  case 64:
    std::get<64>(commands)();
    return;
  case 65:
    std::get<65>(commands)();
    return;
  case 66:
    std::get<66>(commands)();
    return;
  case 67:
    std::get<67>(commands)();
    return;
  case 68:
    std::get<68>(commands)();
    return;
  case 69:
    std::get<69>(commands)();
    return;
  case 70:
    std::get<70>(commands)();
    return;
  case 71:
    std::get<71>(commands)();
    return;
  case 72:
    std::get<72>(commands)();
    return;
  case 73:
    std::get<73>(commands)();
    return;
  case 74:
    std::get<74>(commands)();
    return;
  case 75:
    std::get<75>(commands)();
    return;
  case 76:
    std::get<76>(commands)();
    return;
  case 77:
    std::get<77>(commands)();
    return;
  case 78:
    std::get<78>(commands)();
    return;
  case 79:
    std::get<79>(commands)();
    return;
  case 80:
    std::get<80>(commands)();
    return;
  case 81:
    std::get<81>(commands)();
    return;
  case 82:
    std::get<82>(commands)();
    return;
  case 83:
    std::get<83>(commands)();
    return;
  case 84:
    std::get<84>(commands)();
    return;
  case 85:
    std::get<85>(commands)();
    return;
  case 86:
    std::get<86>(commands)();
    return;
  case 87:
    std::get<87>(commands)();
    return;
  case 88:
    std::get<88>(commands)();
    return;
  case 89:
    std::get<89>(commands)();
    return;
  case 90:
    std::get<90>(commands)();
    return;
  case 91:
    std::get<91>(commands)();
    return;
  case 92:
    std::get<92>(commands)();
    return;
  case 93:
    std::get<93>(commands)();
    return;
  case 94:
    std::get<94>(commands)();
    return;
  case 95:
    std::get<95>(commands)();
    return;
  case 96:
    std::get<96>(commands)();
    return;
  case 97:
    std::get<97>(commands)();
    return;
  case 98:
    std::get<98>(commands)();
    return;
  case 99:
    std::get<99>(commands)();
    return;
  default:
    return;
  }
}

int main() {
  auto commands = make_commands();
  lookup(kHit0, commands);
  lookup(kHit1, commands);
  lookup(kMiss, commands);
  return static_cast<int>(g_sink == 0);
}
